baseurl = "https://uncmbbtrivia.netlify.com/"
languageCode = "en-us"
title = "Jay's Notes"
theme = "hugo-xmin"
googleAnalytics = "UA-113470893-1"
disqusShortname = "jays-notes-1" 
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
preserveTaxonomyNames = true
footnotereturnlinkcontents = "↩"
paginate = 7
rssLimit = 10

[permalinks]
    post = "/post/:year/:month/:day/:slug/"
    note = "/note/:year/:month/:day/:slug/"

[params]
    author = "Jay"
    description = "Mostly About R and UNC MBB Trivia"
    #accent = "#99badd" #caroina blue
    #showBorder = true
    #backgroundColor = "white"
    #font = "Raleway" # should match the name on Google Fonts!
    #highlight = true
    #highlightStyle = "solarized-dark"
    highlightLanguages = ["go", "haskell", "kotlin", "scala", "swift", "R"]
    
[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1

[[menu.main]]
    name = "About"
    url = "/about/"
    weight = 2

#[[menu.main]]
#    name = "Categories"
#    url = "/categories/"
#    weight = 3

[[menu.main]]
    name = "Twitter"
    url = "https://twitter.com/uncmbbtrivia"
    weght = 4

[[menu.main]]
    name = "RSS"
    url = "/index.xml"
