---
title: One year after rstudio::conf 2017
author: Jay
date: '2018-01-29'
slug: one-year-after-rstudio-conf-2017
draft: false
---

It was merely a name [change](https://joongsup.rbind.io/post/blog-at-rbind-io/), but with the new blog address at rbind.io, I'm excited about the fact that I am a blogger who uses his name in his blog address, because I've always considered it to be one of the coolest things you can do online :) And it got me thinking, where did it all start from? After many failed attempts to start and maintain my own blog, how is it that this time, it seems it'll just work? 

A quick answer was [@yihui](https://github.com/yihui) and [blogdown](https://github.com/rstudio/blogdown) package, along with amazing R [community/support](https://github.com/rbind/support), but besides blogging, I knew I did one or two other cool things last year, and quickly I realized that it all started with the rstudio conference I attended in 2017. It's probably not a coincidence that I came to this realization right before the week of rstudio conference 2018, because my twitter feed is all mentions related to the conference. With that I got to think about other cool things I ended up doing last year, particularly since attending the rstudio conference. 



So here is a quick list of other cool things I've done with a brief comments under each, while at and since attending the rstudio conference in January, 2017. I tried to keep them in a chronological order. 

1. Hadley's autograph

I took Hadley's Master R Developer workshop, since having worked with R for a couple of years now, I wanted to write an R package at some point. It was simply a great workshop, and yes I asked for his autograph on the first page of his [Advanced R](http://adv-r.had.co.nz/) book, which he did :)

2. Started using github

I never used github before. I created an account on github some time ago, but never actually used it. After taking the training and listening to the talks at the conference, I decided not only to start using it, but to use it frequently. Version control was never a part of my education/work, and I think it's great seeing many folks having pushed/pusing for the inclusion of this topic in data science/statistics curriculum these days. This is just one of those things that I wish I had learned while at school. 

3. Wrote my first R (data) package [uncmbb](https://cran.r-project.org/web/packages/uncmbb/index.html), now available on CRAN

One of the coolest things I've always considered as an avid R user is having your own R package available on CRAN. Hadley's Master R Developer workshop was the single biggest reason I wanted to attend the conference in 2017, and not so long after the conference, I had my first R package up on CRAN. I'm planning to write about starting your data analysis journey with creating an R data packge of your own. 

4. Started preaching R package, tidyverse, and reproducible research (RR) at work

I've been the R guy at work even before the rstudio conference, but after attending the Hadley's training and embracing the idea of developing R packages for projects especially for the purpose of doing reproducible research (casually, I call it reproducible work instead) over other work artifacts and habits, I'm that R guy even more who's introducing tidyverse approach and sharing tips for doing reproducible work. Again, I'm hoping to write about data analysis workflow that I came to settle on that helps with doing RR at work. 

5. Started having a second thought about R packages and tinkered with .Rprofile

As I tried to incorporate R packages for projects at work, soon I ran into several roadblocks mainly due to inherent limitations of corporate world. I'm planning to write about this some time later too, but the main issue was that there are times that I can't use RStudio IDE at work and instead have to work with other tools, mainly in R command line in company servers (which I'm happy with, but not at the same level as using RStudio IDE). Since I wasn't making a good progress in incorporating packages for projects, I started using .Rprofile files to put frequently used functions in one place, but surely I ended up running into the challenges of easily sharing my work with team members. 

6. Turned around once again and made a second R package, primarily for use at work (local).

Not long after I shared my frustration with the difficulty of R package development under corporate environment and my use of .Rprofile file with my team members, I found a way to solve the particular problems I was having. I ended up ditching the use of .Rprofile file completely, and now when I run into such challenges (that are inherent to large company environments), I try to find a solution within existing limitations somehow. Definitely, many times working in a corporate environment can be inefficient and slow, but it's still no reason to use .Rprofile for frequently used functions. 

7. Started a blog, now using rbind.io subdomain. 

At the conference, I didn't really pay attention to [@yihui](https://github.com/yihui)'s talks on blogdown. As my first R package became available on CRAN, however, I wanted to share a couple of quick data analyses that can be done with the data, and quickly I ran into a couple of how-to's using blogdown. There's been many failed attempts to create and maintain my own blog in the past, but I was able to start blogging and keep doing it still, thanks to [@yihui](https://github.com/yihui) and other great folks in R community. 



Unfortunately, I'm not going to the rstudio conference this year (training/conference schedule just didn't work out), and boy do I want to be there this week. For those of you lucky attendees, I hope you make the best out of the conference and enjoy everything you get to learn from amazing people and do your own cool/amazing things after the conference. 

I know you will :)

