---
title: Blog at rbind.io
author: Jay
date: '2018-01-29'
slug: blog-at-rbind-io
categories: []
tags: []
draft: false
---

This weekend, I made a small but meaningful change to the blog that I started late last year. Initially, my blog was named UNCMBBTRIVIA to emphasize to the readers that this blog is about my beloved UNC Men's Basketball team's trivia. But I always wanted to have a blog where I write not only about UNC MBB trivia, but more importantly about data analysis and R. 

As I thought about it more, it became clear that I'd better drop the UNCMBBTrivia-only identity of the blog to start writing more about data analysis and R, and ever since then I've been thinking about how and when to make the change. Searching for ideas, this Friday I was reading this and that, and bam! I ran into Yihui's online blogdown book, in which he introduced *.rbind.io subdomain option for deployment (via netlify, which was my original choice). 

Everything about *.rbind.io option was just right for what I wanted: moving away from UNCMBBTrivia-only identity, showing a taste of data-powered contents of the blog, and being more active in the R community (who among useRs are not excited about interacting with @yihui, @hadley, @drob, and many more amazing folks in R community?)

So this weekend, I jumpted the gun and created an issue on rbind support github, which is what one needs to do to request for an rbind.io subdomain. To my pleasant surprise, @road2stat responded to my request quickly, and less than 24 hours later, the new blog address is joongsup.rbind.io :) (I wonder if there's a way to automatically redirect the visit to the original netlify address to the new rbind.io one?)

I couldn't be happier with the whole experience, and am looking forward to sharing my journey in data analysis and R in addition to UNCMBBTrivia here. 

