---
title: RSS feed and rbind github repo
author: Jay
date: '2018-02-06'
slug: rss-feed
categories: [R]
tags: [blog, rss, feed, r weekly]
draft: false
---

[Maëlle Salmon](https://twitter.com/ma_salmon/status/957902480549040128) reminded me to submit posts/blog RSS feed to R [weekly](https://rweekly.org/submit) on my [tweet](https://twitter.com/uncmbbtrivia/status/957892046676811777), and I set out to do just that. I didn't have much understanding as to how to though, and googling things like "how to generate rss feed in xmin blogdown" didn't really turn up anything useful for new bloggers like me. Maybe it's a quite straighforward knowledge that my full blog url is not a valid RSS feed address, but I got to know that only after checking my blog url from the R weekly submit [page](https://validator.w3.org/feed/). And besides, I'm pretty sure for most blogs that I wanted to add to my Feedly, entering their url address worked just fine, and it was a bit of a head scratcher. 

A bit of digression before getting into how I was able to turn on RSS feed. Since my main excitement with blogdown was being able to focus on content generation (mostly about data science and UNC basketball) and not having to worry about the site set-up, deployment, etc., I naturally followed Yihui's recommneded [workflow](https://bookdown.org/yihui/blogdown/workflow.html) of using netlify for the site deployment. I was very pleased with how easy it was to start my own blog and kept going for quite some time. Then I quickly ran into a little identity [crisis](https://joongsup.rbind.io/post/2018/01/29/blog-at-rbind-io/) (as my netlify subdomain was "uncmbbtrivia"^[I understand I could've changed the netlify subdomain, but opted to rbind anyway.]), and I decided to get a subdomain under rbind.io, which I had known about before. With the domain change, I'd change my subdomain name too, I figured. 

So I set out to switch over to rbind.io and ran into rbind support's about [page](https://support.rbind.io/about/). I opened a [ticket](https://github.com/rbind/support/issues/145), and [Nan Xiao](https://github.com/road2stat) quickly helped me with .rbind.io subdomain creation, and now my blog's at rbind just like that^[The netlify address still works, but it forwards to rbind. Notes on forwarding [here](https://yihui.name/en/2017/11/301-redirect/), thanks to @yihui.]. Without a doubt, it was a very pleasant experience, and I was all set. 

Except that my source files were still residing in my person github account, when I had expected that the source repo would have somehow automatically transferred to rbind github account when my rbind.io subdomain was created. At least that's how I read the how to join rbind [section](https://support.rbind.io/about/) in the about page, but it wasn't the case, and I ended up transferring my blog source repo to rbind organization repo on github, literally with a click of a button^[And I think I need to change my local git setting too, at least that's the message I get whenever I commit/push changes, although it seems like it's not critical at the moment.]. So I joined the other 150+ people (or 60+ repos) that are hosted under rbind github account.  

Back to the RSS feed story, so I needed some quick help on how to generate an RSS feed, and I could've just fired up a question on twitterverse and/or opened a ticket on rbind github, but I decided to make use of the rbind repo. These are the people who more or less have the same interest as me, especially in using R for data science and also likely blogdown for blogging, so I should be able to find some clues as to how to generate an RSS feed, I figured. 

And I did find what I was missing there! I noticed that I didn't have /layouts/rss.xml file^[Maybe it was not needed, and I could've turned on RSS feed somehow differently?]. Once I manually added the file and inserted a couple of lines in my /layouts/partials/header.html, I was all set, and my RSS feed was generated successfully for now^[When I validated the RSS link, it gave me some recommendations, and I haven't spent time to address them yet, but they don't seem to be errors.].

So there, I was happy to have my blog subdomain in .rbind.io^[Besides the new name, my other attraction to rbind.io is that rbind.io address automatically tells the world that the blogger cares for R.], and I'm also happy to have my source repo under rbind github account, which can "make it easier to discover websites and get inspirations from other people's websites", and "...may study its source files, or even ask the author via Github issues."


