---
title: 2021 external speaking, hugo-xmin, and distill
author: Jay
date: '2021-02-14'
slug: 2021-external-speaking-hugo-xmin-and-distill
categories: []
tags:
  - hugo
  - presentation
  - xmin
  - distill
draft: true
---

Each year I try to do at least one [external presentation](https://joongsup.rbind.io/post/2018/07/22/external-presentation-goal/). It's probably not an exaggeration that if it wasn't for an external speaking engagement that I got myself into this year, there would not have been the last post, which was the first in almost a year. Sure last weekend was special because Tar Heels beat Duke and was the only blue blood that came out with a W^[And of course they are the only blue blood with a L today :(] that day, so in a sense it was a good day to get back to writing and yes, I'm planning to keep writing here, but I still find it hard to write as often as before, not that I was a prolific writer by any measure. Guess it says something about my priorities these days. 

The external speaking engagement goal pushed me to write a post, mainly because one of the things I was going to talk about was blogging. I wanted to walk the talk as I had intended to (and did) mention blogging as a good way to showcase interests and skills in one's journey as a data professional :D 

As part of the prep for the talk, I had to look up a couple of things (mainly needed a reminder on xaringan and how to share the deck online), and one [blog](https://timmastny.rbind.io/blog/embed-slides-knitr-blogdown/) caught my eye. It was using the same source theme (Yihui's hugo-xmin) as mine, just slightly different. I especially liked the part where posts were grouped by year in their own "blog" page. So I started checking it out, and planned to tweak my blog here and there to make my blog look something like that.

As I was reading through several other blogs on tips on updating blog layouts/themes, I ran into Distill^[https://blog.rstudio.com/2020/12/07/distill/], another R package helpful for blogging (among others). It seems its predecessor was available since long time ago, and it's gotten a new name recently. Also it seems to be a response from RStudio to all the issues generated by breaking changes (?) by Hugo updates. I don't know what they are exactly, but it seems like the recent Hugo updates have caused some troubles with blogdown, as evidenced by sudden unease of working on a new post (compared to about a year ago) and the [note](https://bookdown.org/yihui/blogdown/) from the blogdown authors.

So seems like I have some following/reading up to do and consider moving from Hugo based blogging to distill based one!